services:
  shork-486-build:
    build: .
    command:
      - --always-build
      - --is-debian
      - --target-disk=72
      - --target-swap=8
      - --fix-extlinux
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
      - IN_DOCKER=1
    privileged: true
    volumes:
      - ./.git:/var/shork-486/.git
      - ./shork-486:/var/shork-486
